apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-slowstart
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.243.0.0/16
    services:
      cidrBlocks:
        - 10.95.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: KamajiControlPlane
    name: capi-slowstart-kubevirt
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtCluster
    name: capi-slowstart
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  annotations:
    cluster.x-k8s.io/managed-by: kamaji
  name: capi-slowstart
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: capi-slowstart-kubevirt
  namespace: default
spec:
  addons:
    coreDNS:
      dnsServiceIPs:
        - 10.95.0.10
    konnectivity: {}
    kubeProxy: {}
  dataStoreName: default
  deployment: null
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
      - InternalIP
      - ExternalIP
  network:
    serviceAnnotations:
      kube-vip.io/loadbalancerIPs: 0.0.0.0
    serviceType: LoadBalancer
  replicas: 2
  version: v1.30.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: capi-slowstart-md-0
  namespace: default
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: none
      virtualMachineTemplate:
        spec:
          dataVolumeTemplates:
            - metadata:
                name: capik-md-0-boot-volume
              spec:
                pvc:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 20Gi
                  storageClassName: hvl
                source:
                  registry:
                    url: docker://quay.io/capk/ubuntu-2204-container-disk:v1.30.1
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 4
                  sockets: 1
                  threads: 1
                devices:
                  disks:
                    - disk:
                        bus: virtio
                      name: containervolume
                  interfaces:
                    - bridge: {}
                      model: virtio
                      name: secondary
                    - bridge: {}
                      model: virtio
                      name: default
                resources:
                  limits:
                    cpu: 4
                    memory: 16Gi
                  requests:
                    cpu: 4
                    memory: 16Gi
              evictionStrategy: External
              networks:
                - multus:
                    networkName: default/vmnet
                  name: secondary
                - name: default
                  pod: {}
              volumes:
                - dataVolume:
                    name: capik-md-0-boot-volume
                  name: containervolume
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: capi-slowstart-md-0
  namespace: default
spec:
  template:
    spec:
      users:
        - name: myuser                  # e.g. your preferred username
          sudo: ALL=(ALL) NOPASSWD:ALL  # optional: give sudo without password
          sshAuthorizedKeys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzc0+9R4uEmf81h7yrkyM750HF1pMyo5LSx5oXL2VA1/4fP4+FZ7zHQi+0azkyeybEvBqR8ga4NIeRO2gYVnz9TCorGBzpHIcRZ4A0+tGBD2/nD6bRJJ98koNRSJX5/R8fBfxUSdK4pSTkP5d7wk8ZFeo+S47tHY9hSHGskTdSs6IGsQy535hxazJViKVP63oMlOB4tZ9s6TKnlAsty+Ev+aQie6Rg/wW4ybx9Ju62Alzgrt9b8HQzFDz0vBUOzhiqgnKS9KLrmYWJjro49nlEILkO6XCSelagHTcsB+PEvCbcJqCITJ4o1x976sWaPVSiJ5kX2WD5cdraAUsfTYVq34Dn3cZFMQSmLCxdXPTBGAsbOPL6xXFX8IcytJ4zTCQE+F5qe5dy3CfVyQKOgAe49znguKiB3WFeg1wU0P5Gpm+mW/2+4jAz5V+ia/PZPe4jyeJh2OzN2LNE+cWq8S2CZDVoliX7FExTky8/AlqrOvXDD6gq4sIwhKBLW3At6TTE3C0Yu9sySOfvtRMTgMYa1Dmi371rLacPtCFt1Or/RHpJSt9ablPuAMpjn+hix8SnSfHSD4wkNN3p9P2K+gDpgZFwNQNZbu6pn9b1dUPgqmudXNY8ZQcSI73IpznnVMfNAHynNLYrahamSs0L0nCIwgZ7yVmYJyLCXRWqMwKBpQ== suman@appscode.com
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: capi-slowstart-md-0
  namespace: default
spec:
  clusterName: capi-slowstart
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: capi-slowstart-md-0
          namespace: default
      clusterName: capi-slowstart
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: KubevirtMachineTemplate
        name: capi-slowstart-md-0
        namespace: default
      version: v1.30.1