apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: capi-slowstart
  namespace: new
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.243.0.0/16
    services:
      cidrBlocks:
        - 10.95.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KamajiControlPlane
    name: capi-slowstart-kubevirt
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: KubevirtCluster
    name: capi-slowstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  annotations:
    cluster.x-k8s.io/managed-by: kamaji
  name: capi-slowstart
  namespace: new
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha2
kind: KamajiControlPlane
metadata:
  name: capi-slowstart-kubevirt
  namespace: new
spec:
  controllerManager:
    extraArgs:
      - --cloud-provider=external
  addons:
    coreDNS:
      dnsServiceIPs:
        - 10.95.0.10
    konnectivity: {}
    kubeProxy: {}
  dataStoreName: default
  deployment: null
  kubelet:
    cgroupfs: systemd
    configurationJSONPatches:
      - op: remove
        path: /crashLoopBackOff
      - op: remove
        path: /imagePullCredentialsVerificationPolicy
      - op: remove
        path: /memoryReservationPolicy
      - op: remove
        path: /mergeDefaultEvictionSettings
  network:
    serviceAnnotations:
      kube-vip.io/loadbalancerIPs: 0.0.0.0
    serviceType: LoadBalancer
  replicas: 2
  version: 1.34.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: capi-slowstart-md-0
  namespace: new
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: none
      virtualMachineTemplate:
        metadata:
          annotations:
            openstack-network-id: "e31344bd-5840-4e67-b9f4-42f2d022655c"
            openstack-security-groups: '["disable"]'
            openstack-subnet-ids: '["34ae98d5-c02d-48f7-a525-19dc6ea10032"]'
        spec:
          dataVolumeTemplates:
            - metadata:
                name: capik-md-0-boot-volume
              spec:
                pvc:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 20Gi
                  storageClassName: hvl
                source:
                  registry:
                    url: "docker://quay.io/capk/ubuntu-2404-container-disk:v1.34.1"
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 4
                  sockets: 1
                  threads: 1
                devices:
                  disks:
                    - disk:
                        bus: virtio
                      name: containervolume
                  interfaces:
                    - bridge: {}
                      model: virtio
                      name: default
                memory:
                  guest: 16Gi
                resources:
                  limits:
                    cpu: 4
                    memory: 16Gi
                  requests:
                    cpu: 4
                    memory: 16Gi
              evictionStrategy: External
              networks:
                - pod: {}
                  name: default
              volumes:
                - dataVolume:
                    name: capik-md-0-boot-volume
                  name: containervolume
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: capi-slowstart-md-0
  namespace: new
spec:
  template:
    spec:
      preKubeadmCommands:
        - apt-get update
        - apt-get install -y qemu-guest-agent
        - systemctl enable --now qemu-guest-agent.service
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            - name: "cloud-provider"
              value: "external"
      users:
        - name: myuser
          sudo: ALL=(ALL) NOPASSWD:ALL
          sshAuthorizedKeys:
            - ssh ....
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: capi-slowstart-md-0
  namespace: new
spec:
  clusterName: capi-slowstart
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: capi-slowstart-md-0
      clusterName: capi-slowstart
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: KubevirtMachineTemplate
        name: capi-slowstart-md-0
      version: 1.34.1