apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: capi-slowstart
  namespace: new1
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.243.0.0/16
    services:
      cidrBlocks:
        - 10.95.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KamajiControlPlane
    name: capi-slowstart-kubevirt
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: KubevirtCluster
    name: capi-slowstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  annotations:
    cluster.x-k8s.io/managed-by: kamaji
  name: capi-slowstart
  namespace: new1
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha2
kind: KamajiControlPlane
metadata:
  name: capi-slowstart-kubevirt
  namespace: new1
spec:
  addons:
    coreDNS:
      dnsServiceIPs:
        - 10.95.0.10
    konnectivity: {}
  dataStoreName: default
  deployment: null
  kubelet:
    cgroupfs: systemd
    configurationJSONPatches:
      - op: remove
        path: /crashLoopBackOff
      - op: remove
        path: /imagePullCredentialsVerificationPolicy
      - op: remove
        path: /memoryReservationPolicy
      - op: remove
        path: /mergeDefaultEvictionSettings
  network:
    serviceAnnotations:
      kube-vip.io/loadbalancerIPs: 0.0.0.0
    serviceType: LoadBalancer
  replicas: 2
  version: 1.34.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: capi-slowstart-md-0
  namespace: new1
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: none
      virtualMachineTemplate:
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 4
                  sockets: 1
                  threads: 1
                devices:
                  disks:
                    - disk:
                        bus: virtio
                      name: containervolume
                  interfaces:
                    - bridge: {}
                      model: virtio
                      name: default
                memory:
                  guest: 16Gi
                resources:
                  limits:
                    cpu: 4
                    memory: 16Gi
                  requests:
                    cpu: 4
                    memory: 16Gi
              evictionStrategy: External
              networks:
                - pod: {}
                  name: default
              volumes:
                - containerDisk:
                    image: "quay.io/capk/ubuntu-2404-container-disk:v1.34.1"
                  name: containervolume
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: capi-slowstart-md-0
  namespace: new1
spec:
  template:
    spec:
      preKubeadmCommands:
        - apt-get update
        - apt-get install -y qemu-guest-agent
        - systemctl enable --now qemu-guest-agent.service
      users:
        - name: myuser
          sudo: ALL=(ALL) NOPASSWD:ALL
          sshAuthorizedKeys:
            - ssh-rsa ...
            - ssh-rsa ..
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: capi-slowstart-md-0
  namespace: new1
spec:
  clusterName: capi-slowstart
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: capi-slowstart-md-0
      clusterName: capi-slowstart
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: KubevirtMachineTemplate
        name: capi-slowstart-md-0
      version: 1.34.1