apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: lb-cluster
  namespace: new
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.243.0.0/16
    services:
      cidrBlocks:
        - 10.95.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KamajiControlPlane
    name: lb-cluster-kubevirt
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: KubevirtCluster
    name: lb-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  annotations:
    cluster.x-k8s.io/managed-by: kamaji
  name: lb-cluster
  namespace: new
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha2
kind: KamajiControlPlane
metadata:
  name: lb-cluster-kubevirt
  namespace: new
spec:
  addons:
    coreDNS:
      dnsServiceIPs:
        - 10.95.0.10
    konnectivity: {}
  dataStoreName: default
  deployment: null
  kubelet:
    preferredAddressTypes:
      - InternalIP
      - ExternalIP
    cgroupfs: systemd
    configurationJSONPatches:
      - op: remove
        path: /crashLoopBackOff
      - op: remove
        path: /imagePullCredentialsVerificationPolicy
      - op: remove
        path: /memoryReservationPolicy
      - op: remove
        path: /mergeDefaultEvictionSettings
  network:
    serviceAnnotations:
      kube-vip.io/loadbalancerIPs: 0.0.0.0
    serviceType: LoadBalancer
  replicas: 3
  version: 1.34.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: lb-cluster-md-0
  namespace: new
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: none
      virtualMachineTemplate:
        metadata:
          annotations:
            openstack-project-id: "779d9954e19740f99d2b5be81976bedc"
            openstack-network-id: "3f09e930-bfab-4828-b12e-00f68a63764e"
            openstack-subnet-id: "91c108e9-8be7-47b0-ab9b-e4803f9860a8"
            openstack-security-groups: '["disable"]'
        spec:
          dataVolumeTemplates:
            - metadata:
                name: capik-md-0-boot-volume
              spec:
                pvc:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 20Gi
                  storageClassName: hvl
                source:
                  registry:
                    url: "docker://quay.io/capk/ubuntu-2404-container-disk:v1.34.1"
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 8
                  sockets: 1
                  threads: 1
                devices:
                  disks:
                    - disk:
                        bus: virtio
                      name: dv-volume
                  interfaces:
                    - bridge: {}
                      model: virtio
                      name: default
                memory:
                  guest: 16Gi
                resources:
                  limits:
                    cpu: 8
                    memory: 16Gi
                  requests:
                    cpu: 8
                    memory: 16Gi
              evictionStrategy: External
              networks:
                - pod: {}
                  name: default
              volumes:
                - dataVolume:
                    name: capik-md-0-boot-volume
                  name: dv-volume
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: lb-cluster-md-0
  namespace: new
spec:
  template:
    spec:
      preKubeadmCommands:
        - apt-get update
        - apt-get install -y qemu-guest-agent
        - systemctl enable --now qemu-guest-agent.service
      postKubeadmCommands:
        - |
          MGTIP=$(ip -4 -o addr show enp1s0 | awk '{print $4}' | cut -d/ -f1)
          mkdir -p /etc/systemd/system/ssh.socket.d
          printf '[Socket]\nListenStream=\nListenStream=%s:22\n' "$MGTIP" > /etc/systemd/system/ssh.socket.d/override.conf
          systemctl daemon-reload
          systemctl restart ssh.socket
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/cpu: "4"
    capacity.cluster-autoscaler.kubernetes.io/memory: 8Gi
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "8"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
  name: lb-cluster-md-0
  namespace: new
spec:
  clusterName: lb-cluster
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: lb-cluster-md-0
      clusterName: lb-cluster
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: KubevirtMachineTemplate
        name: lb-cluster-md-0
      version: 1.34.1